Load Data

In [1]:
from sklearn.datasets import load_iris
iris_datasets = load_iris()

In [2]:
print("Jenis isian dari datasets iris = \n {}".format(iris_datasets.keys()))

Jenis isian dari datasets iris = 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [3]:
print("target name = {}".format(iris_datasets['target_names']))

target name = ['setosa' 'versicolor' 'virginica']


In [4]:
print("feature name = {}".format(iris_datasets['feature_names']))

feature name = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [18]:
print("data = \n{}".format(iris_datasets['data'][:5]))

data = 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [9]:
print("target = \n{}".format(iris_datasets['target'])) #jenis bunga iris
# 0 = setosa, 1 = Versicolor, 2 = Virginica

target = 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [14]:
#melihat tipe data
print("Tipe Data = {}".format(type(iris_datasets['data'])))
print("Tipe Target = {}".format(type(iris_datasets['target'])))

Tipe Data = <class 'numpy.ndarray'>
Tipe Target = <class 'numpy.ndarray'>


In [20]:
print("Ukuran Data = {}".format(iris_datasets['data'].shape)) #150 baris dan 4 kolom
print("Ukuran Target = {}".format(iris_datasets['target'].shape)) #150 baris dan 1 kolom

Ukuran Data = (150, 4)
Ukuran Target = (150,)


# proses training dan testing

membagi 150 data menjadi data untuk training dan data untuk testing

dicoba membagi data training (75%) dan data testing (25%)

In [23]:
from sklearn.model_selection import train_test_split
#x = data, y =target
x_train, x_test, y_train, y_test = train_test_split(
    iris_datasets['data'],iris_datasets['target'],test_size= 0.25, random_state = 0)
#random_state = 0 -> kalau di run ulang, isi data yang dibagi tetap sama

In [25]:
#jumlah data training
print("x_train shape: {}" .format(x_train.shape)) #data = (sepal length, sepal width, petal length, petal width)
print("y_train shape: {}" .format(y_train.shape)) #target = (sentosa, versicolor, virginica)

x_train shape: (112, 4)
y_train shape: (112,)


In [27]:
#jumlah data training
print("x_test shape: {}" .format(x_test.shape)) #data = (sepal length, sepal width, petal length, petal width)
print("y_test shape: {}" .format(y_test.shape)) #target = (sentosa, versicolor, virginica)

x_test shape: (38, 4)
y_test shape: (38,)


In [28]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [29]:
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [33]:
import numpy as np
x_baru = np.array([[5, 2.1, 1, 4.2]])
prediksi = knn.predict(x_baru)
print("hasil prediksi KNN = {}".format(prediksi))
print("hasil prediksi nama bunga = {}".format(iris_datasets['target_names'][prediksi]))

hasil prediksi KNN = [1]
hasil prediksi nama bunga = ['versicolor']


# Evaluasi Model

In [35]:
y_pred = knn.predict(x_test)
print(y_pred)

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [36]:
print("hasil akurasi model = {}".format(knn.score(x_test, y_test)))
#hasil akurasi 97%

hasil akurasi model = 0.9736842105263158


#Mencoba data training 90% dan data testing 10%

In [64]:
from sklearn.model_selection import train_test_split
#x = data, y =target
x_train, x_test, y_train, y_test = train_test_split(
    iris_datasets['data'],iris_datasets['target'],test_size= 0.1, random_state = 0)
#random_state = 0 -> kalau di run ulang, isi data yang dibagi tetap sama

In [66]:
#jumlah data training
print("x_train shape: {}" .format(x_train.shape)) #data = (sepal length, sepal width, petal length, petal width)
print("y_train shape: {}" .format(y_train.shape)) #target = (sentosa, versicolor, virginica)

x_train shape: (135, 4)
y_train shape: (135,)


In [67]:
#jumlah data training
print("x_test shape: {}" .format(x_test.shape)) #data = (sepal length, sepal width, petal length, petal width)
print("y_test shape: {}" .format(y_test.shape)) #target = (sentosa, versicolor, virginica)

x_test shape: (15, 4)
y_test shape: (15,)


In [68]:
from sklearn.neighbors import KNeighborsClassifier
knn2 = KNeighborsClassifier(n_neighbors = 1)

In [69]:
knn2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [70]:
print("hasil akurasi model = {}".format(knn2.score(x_test, y_test)))
#hasil akurasi 97%

hasil akurasi model = 1.0


#Tugas

In [25]:
from sklearn.datasets import load_breast_cancer
cancer_datasets = load_breast_cancer()

In [26]:
print("Jenis isian dari datasets iris = \n {}".format(cancer_datasets.keys()))

Jenis isian dari datasets iris = 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [27]:
print("target name = {}".format(cancer_datasets['target_names']))

target name = ['malignant' 'benign']


In [28]:
print("feature name = {}".format(cancer_datasets['feature_names']))

feature name = ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']


In [29]:
print("data = \n{}".format(cancer_datasets['data'][:30]))

data = 
[[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01 2.776e-01 3.001e-01
  1.471e-01 2.419e-01 7.871e-02 1.095e+00 9.053e-01 8.589e+00 1.534e+02
  6.399e-03 4.904e-02 5.373e-02 1.587e-02 3.003e-02 6.193e-03 2.538e+01
  1.733e+01 1.846e+02 2.019e+03 1.622e-01 6.656e-01 7.119e-01 2.654e-01
  4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02 7.864e-02 8.690e-02
  7.017e-02 1.812e-01 5.667e-02 5.435e-01 7.339e-01 3.398e+00 7.408e+01
  5.225e-03 1.308e-02 1.860e-02 1.340e-02 1.389e-02 3.532e-03 2.499e+01
  2.341e+01 1.588e+02 1.956e+03 1.238e-01 1.866e-01 2.416e-01 1.860e-01
  2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01 1.599e-01 1.974e-01
  1.279e-01 2.069e-01 5.999e-02 7.456e-01 7.869e-01 4.585e+00 9.403e+01
  6.150e-03 4.006e-02 3.832e-02 2.058e-02 2.250e-02 4.571e-03 2.357e+01
  2.553e+01 1.525e+02 1.709e+03 1.444e-01 4.245e-01 4.504e-01 2.430e-01
  3.613e-01 8.758e-02]
 [1.142e+01 2.038e+01 7.758e+01 3.861e+02 1.425e-01 2.839e-

In [30]:
print("target = \n{}".format(cancer_datasets['target']))

target = 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 

In [31]:
#melihat tipe data
print("Tipe Data = {}".format(type(cancer_datasets['data'])))
print("Tipe Target = {}".format(type(cancer_datasets['target'])))

Tipe Data = <class 'numpy.ndarray'>
Tipe Target = <class 'numpy.ndarray'>


In [32]:
print("Ukuran Data = {}".format(cancer_datasets['data'].shape)) #569 baris dan 30 kolom
print("Ukuran Target = {}".format(cancer_datasets['target'].shape)) #569 baris dan 1 kolom

Ukuran Data = (569, 30)
Ukuran Target = (569,)


#proses training dan testing

In [43]:
from sklearn.model_selection import train_test_split
#x = data, y =target
x_train, x_test, y_train, y_test = train_test_split(
    cancer_datasets['data'],cancer_datasets['target'],test_size= 0.25, random_state = 0) #data training 75% dan data testing 25%
#random_state = 0 -> kalau di run ulang, isi data yang dibagi tetap sama

In [44]:
from sklearn.neighbors import KNeighborsClassifier
knn2 = KNeighborsClassifier(n_neighbors = 1)

In [45]:
knn2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [46]:
import numpy as np
x_baru2 = np.array(([[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0,
                     11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0,
                     21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0]]))
prediksi2 = knn2.predict(x_baru2)
print("hasil prediksi KNN = {}".format(prediksi2))
print("hasil prediksi nama cancer = {}".format(cancer_datasets['target_names'][prediksi2]))

hasil prediksi KNN = [1]
hasil prediksi nama cancer = ['benign']


#evaluasi model

In [47]:
y_pred2 = knn2.predict(x_test)
print(y_pred2)

[1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0 0 0 1 1 1 0 1 1 1 1 0 1 0 1 0 1 0 1
 0 1 0 0 1 0 1 0 0 1 1 1 0 0 1 0 1 1 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 1 0 1 1
 0 1 1 1 1 1 0 0 0 1 0 1 1 1 0 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 1 1
 0 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 1 0]


In [48]:
print("hasil akurasi model = {}".format(knn2.score(x_test, y_test)))

hasil akurasi model = 0.916083916083916
